const lessonsData = [
  {
    id: 1,
    time: "09:00-11:00",
    weekDay: "Monday",
    type: "Group",
    name: "General English",
    description: "Clarity is key",
    teacher: "Hajizada Farid",
  },
  {
    id: 2,
    time: "11:00-13:00",
    weekDay: "Tuesday",
    type: "Private",
    name: "Advanced English",
    description: "Improving language skills",
    teacher: "Anna Smith",
  },
  {
    id: 3,
    time: "13:00-15:00",
    weekDay: "Wednesday",
    type: "Group",
    name: "Business English",
    description: "Focus on professional communication",
    teacher: "John Doe",
  },
  {
    id: 4,
    time: "15:00-17:00",
    weekDay: "Thursday",
    type: "Private",
    name: "IELTS Preparation",
    description: "Preparing for the IELTS exam",
    teacher: "Emily Johnson",
  },
  {
    id: 5,
    time: "17:00-19:00",
    weekDay: "Friday",
    type: "Group",
    name: "Conversational English",
    description: "Practice speaking and listening skills",
    teacher: "Michael Brown",
  },
  {
    id: 6,
    time: "19:00-21:00",
    weekDay: "Saturday",
    type: "Group",
    name: "TOEFL Preparation",
    description: "Preparing for the TOEFL exam",
    teacher: "Sophia White",
  },
  {
    id: 7,
    time: "21:00-23:00",
    weekDay: "Monday",
    type: "Private",
    name: "English Literature",
    description: "Exploring classic and modern literature",
    teacher: "Daniel Green",
  },
  {
    id: 8,
    time: "09:00-11:00",
    weekDay: "Sunday",
    type: "Private",
    name: "Grammar Workshop",
    description: "Deep dive into English grammar",
    teacher: "Olivia Robinson",
  },
  {
    id: 9,
    time: "11:00-13:00",
    weekDay: "Tuesday",
    type: "Group",
    name: "English for Kids",
    description: "Learning English through games and activities",
    teacher: "William Brown",
  },
  {
    id: 10,
    time: "13:00-15:00",
    weekDay: "Wednesday",
    type: "Group",
    name: "English for Teens",
    description: "Learning English through games and activities",
    teacher: "Oliver Smith",
  },
  {
    id: 11,
    time: "15:00-17:00",
    weekDay: "Monday",
    type: "Private",
    name: "English for Adults",
    description: "Learning English through games and activities",
    teacher: "Emma Johnson",
  },
  {
    id: 12,
    time: "17:00-19:00",
    weekDay: "Thursday",
    type: "Group",
    name: "English for Seniors",
    description: "Learning English through games and activities",
    teacher: "Ava Williams",
  },
];

export default lessonsData;
